**Step-1:Loading & Reading the dataset**

In [8]:
import pandas as pd
df=pd.read_csv("/content/Combined_dataset.csv")

In [10]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

**Step-2:Exploration of Data**

In [9]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [11]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [12]:
df.shape

(1000, 24)

In [13]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [14]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

The dataset was first loaded into a Pandas DataFrame so that it could be analyzed and processed efficiently. To get an initial understanding of the data, the head() function was used to display the first five rows and confirm that the dataset had been imported correctly. Similarly, the tail() function was used to view the last five rows.

The dataset's dimensions were checked using the shape attribute, which showed that it contains 1,000 rows and 24 columns. The columns attribute was then used to review all the available features, including details related to products, pricing, ratings, sellers, and categories.

To better understand the structure of the dataset, dtypes and info() were used to inspect the data types of each column and identify any missing values or inconsistencies that might require cleaning before further analysis.

**Step-3:Handling Missing values**

In [16]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [17]:
df=df.drop(columns=['videos'])

In [18]:
numerical_cols=df.select_dtypes(include=['number']).columns
numerical_cols
df[numerical_cols]=df[numerical_cols].fillna(df[numerical_cols].median())

In [19]:
text_cols=df.select_dtypes(include=['object']).columns
text_cols
df[text_cols]=df[text_cols].fillna("Unknown")

In [20]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

The videos column was removed from the dataset because a large portion of its values (approximately 78.1%) were missing, making the column unreliable for analysis. To handle the remaining missing data, the median was used to fill missing values in numeric columns, as it is less affected by extreme values. For categorical and text-based columns, missing entries were replaced with "Unknown", ensuring that valuable records were retained while maintaining the overall integrity of the dataset.

**Step 4:Basic Operations**

In [21]:
selected_data=df[['title','rating','final_price','category']]
selected_data

              title  rating   final_price   category
0       Lino Perros     3.8   "₹3,995.00"  backpacks
1    Tommy Hilfiger     4.5   "₹2,899.00"  backpacks
2             Lavie     4.4   "₹2,999.00"  backpacks
3            F Gear     4.4   "₹1,675.00"  backpacks
4         MYTRIDENT     4.7   "₹2,899.00"  bath-robe
..              ...     ...           ...        ...
995           KREDO     3.5  "₹11,890.00"    watches
996           GUESS     5.0   "₹8,900.00"    watches
997        GIORDANO     2.8   "₹7,950.00"    watches
998        Fastrack     4.3   "₹2,636.00"    watches
999         BOLDFIT     3.8     "₹699.00"  yoga-mats

[1000 rows x 4 columns]

In [22]:
high_rating=df[df['rating']>4]
high_rating.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,Unknown,"[{""size"":""S""}]",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,Unknown,"[{""size"":""Onesize""}]",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,56.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"[{""specification_name"":""Finish"",""specification...","{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",Unknown,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories

In [ ]:
df['final_price']

0       "₹3,995.00"
1       "₹2,899.00"
2       "₹2,999.00"
3       "₹1,675.00"
4       "₹2,899.00"
           ...
995    "₹11,890.00"
996     "₹8,900.00"
997     "₹7,950.00"
998     "₹2,636.00"
999       "₹699.00"
Name: final_price, Length: 1000, dtype: object

In [23]:
df['final_price']=df['final_price'].str.replace('₹','',regex=False)
df['final_price']=df['final_price'].str.replace(',','',regex=False)
df['final_price']=df['final_price'].str.replace('"','',regex=False)
df['final_price']=df['final_price'].astype(float)

In [ ]:
print(df['final_price'].dtype)

float64

In [24]:
expensive_products=df[df['final_price']>3000]
expensive_products.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]",Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
13,18492504,ROMEE,Blue & Beige Conversational 160 TC King Bedshe...,3.9,10,3499,65.0,3499.0,INR,http://assets.myntassets.com/assets/images/184...,...,"[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",Unknown,Unknown,"[{""size"":""Double King""}]",Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
17,18346134,Arrabi,Pink & Grey Striped 300 TC King Cotton Bedshee...,4.3,12,6329,76.0,6329.0,INR,http://assets.myntassets.com/assets/images/183...,...,"[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",Unknown,Unknown,"[{""size"":""Super King""}]",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599,60.0,3839.0,INR,http://assets.myntassets.com/assets/images/214...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",SAI███USE███OT █████████ NA███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
58,20129438,Skechers,Men Blue Textured Sneakers,3.8,11,12999,30.0,7799.0,INR,http://assets.myntassets.com/assets/images/201...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",LSD███FES███ES █████████IMI██████,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...",118███GH ███H C█████████OGE███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes

Basic data manipulation tasks were carried out using Pandas to better understand and analyze the dataset. Key columns such as product title, rating, final price, and category were selected to focus on the most relevant product details. The data was then filtered to identify products with ratings above 4 as well as products with higher final prices, allowing for a more targeted analysis. These operations helped uncover useful insights from the dataset and demonstrated how specific subsets of data can be extracted efficiently for further exploration and decision-making.

**Step-5:Removing Duplicates**

In [25]:
df.duplicated().sum()

np.int64(0)

Before starting the analysis, the dataset was checked to ensure that the records were unique. No duplicate entries were found, which meant that each row represented a distinct record. As a result, there was no need to remove any data. This confirmed that the dataset was already clean in terms of duplicate records and could be used directly for further analysis.

**Step-6:Creating a derived column**

In [26]:
df['rating_score']=df['rating']*df['ratings_count']
df['rating_score']

0        57.0
1       301.5
2       994.4
3      4628.8
4        56.4
        ...
995      38.5
996     110.0
997      14.0
998      73.1
999     611.8
Name: rating_score, Length: 1000, dtype: float64

A new derived column named rating_score was created by multiplying the product rating by the number of ratings received. This feature combines product quality and popularity into a single metric, which can be useful for identifying highly rated and frequently reviewed products.

**Step-7:Downloading the csv**

In [27]:
df.to_csv('cleaned_dataset.csv',index=False)

In [28]:
from google.colab import files
files.download('cleaned_dataset.csv')